version: "3.7"

services: 
  web:
    container_name: flask_app
    build: 
      context: ./
      dockerfile: Dockerfile
    networks:
      my-network:
        aliases:
          - flask-app
  server:
    container_name: nginx_server
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - 80:80
    networks:
      - my-network
      
networks:
  my-network: