version: "3.7"

services: 
  web:
    container_name: flask_app
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - /home/apps/flask-playground:/home/apps/flask-playground
  server:
    container_name: nginx_server
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - web
    volumes:
      - /home/apps/flask-playground:/home/apps/flask-playground
    ports:
      - 80:80