version: "3.7"

services: 
  web:
    container_name: flask_app
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - shared_data:/home/apps/flask-playground
  server:
    container_name: nginx_server
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - web
    volumes:
      - shared_data:/home/apps/flask-playground
    ports:
      - 80:80

volumes:
  shared_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/apps/flask-playground'